enum WebSocketOpCodeServer {
  WSS_FROM_ANY__PONG__REQUEST = "WSS_FROM_ANY__PONG__REQUEST",
  WSS_FROM__ALL_NEW_MESSAGE__REQUEST = "WSS_FROM__ALL_NEW_MESSAGE__REQUEST",
  WSS_FROM__TEAM_NEW_MESSAGE__REQUEST = "WSS_FROM__TEAM_NEW_MESSAGE__REQUEST",
  WSS_FROM_ANY__GAME_START__REQUEST = "WSS_FROM_ANY__GAME_START__REQUEST",
  WSS_FROM_ANY__WS_DISCONNECTION__RESPONSE = "WSS_FROM_ANY__WS_DISCONNECTION__RESPONSE",
  WSS_FROM_ANY__DISTRIBUTE_DECK__REQUEST = "WSS_FROM_ANY__DISTRIBUTE_DECK__REQUEST",
  WSS_FROM_ANY__JOIN_GAME_UPDATE__REQUEST = "WSS_FROM_ANY__JOIN_GAME_UPDATE__REQUEST",
  WSS_FROM_ANY__WS_CONNECTION__REQUEST = "WSS_FROM_ANY__WS_CONNECTION__REQUEST",
  WSS_FROM_ANY__JOIN_TEAM__REQUEST = "WSS_FROM_ANY__JOIN_TEAM__REQUEST",
  WSS_FROM_ANY__JOIN_GAME__REQUEST = "WSS_FROM_ANY__JOIN_GAME__REQUEST"
}

export default WebSocketOpCodeServer;
